### ISSUE TITLE
Error (Tower strike)

### ISSUE THREAD

**Issue by AsimUdel** [Exawind/amr-wind#1001]
Hello,
I am trying to run @rybchuk tutorial (https://github.com/rybchuk/amr-wind-tutorial/blob/main/03_turbines.md) by using 4 different actuator methods i.e., (FastDisk, Uniform ct disk, Joukowsky disk and FastLine). In the FastLine actuator method (my simulation terminates after ~9 mins of run) giving me the error about the "Tower Strike" (I am attaching screen shot of the error and output file too).
![tower_strike](https://github.com/Exawind/amr-wind/assets/156853074/38b54154-ef37-46b3-a575-1be1523e2408)
[error_log_output_file.txt](https://github.com/Exawind/amr-wind/files/14725697/error_log_output_file.txt)
Did someone get this error in past? and how to remove this ? and also I have not find any relation of different level of grid refinement (like grid point in the most refined level in AMR-Wind documentation), if someone knows please guide me to that. Thank you

**Comment by lawrenceccheung** [comment]
Hi @AsimUdel, 
Did you change any of the input parameters from the original [tutorial file](https://github.com/rybchuk/amr-wind-tutorial/blob/main/03_turbines.md) by @rybchuk, other than switching `TurbineFastDisk` to `TurbineFastLine`?   

One thing that might be an issue is that you are using a larger timestep than recommended for ALM simulations.  Typically the dt for actuator line runs might be 0.01 to 0.02 seconds, and the current dt=0.125 seconds might be more suited for actuator disk runs.  This is not because of a CFL limitation, but more related to how fast each blade is moving per timestep.

Lawrence

**Comment by AsimUdel** [comment]
Hi @lawrenceccheung , great question, I did not change any other input parameter, just switched from TurbineFastDisk to TurbineFastLine, and thank you for the valuable information regarding the dt for FastLine (ALM) case, I will keep that in mind.
