### ISSUE TITLE
trouble in simulations results and some general queries

### ISSUE THREAD

**Issue by AsimUdel** [Exawind/amr-wind#1103]
Hello All,
I have run some simulations for my research (comprised of Spinup, followed by Precursor, and then Turbine). I have some questions and queries:
1) I plotted (wind speed and tke ), and TKE plots gave me some strange results. (Previously, also it seemed like the solution blew when I plotted wind speed with more than one turbines, some of Unstable case plots are 
![Turbine_XZ_tke_plane_0)unstable](https://github.com/Exawind/amr-wind/assets/156853074/71bd438b-7d07-43c0-8f33-1b9215348fd3)
e) 
![Turbine_tke_xy_unstable](https://github.com/Exawind/amr-wind/assets/156853074/15485668-cc5d-4f17-813b-d8acc3e83303)
input files are:
[Precursor_unstable_.txt](https://github.com/user-attachments/files/15888375/Precursor_unstable_.txt)
[Spinup_unstable.txt](https://github.com/user-attachments/files/15888376/Spinup_unstable.txt)

2) Also, when I wanted to run “no turbine” simulations with the same times step as the turbine simulations, after (almost at 250s for Stable case, and 660s for Unstable,  solutions blew up and stopped calculated variable i.e., velocity, tke, etc) 
![Unstable_no_turbine](https://github.com/Exawind/amr-wind/assets/156853074/e9b5b64a-5476-4209-aae1-ff3b967f882d)
![Stable_no_turbine](https://github.com/Exawind/amr-wind/assets/156853074/f4eeaa94-cd3d-4174-93bd-2e3955ea98b6)
Input files are
[No_turbine_stable_.txt](https://github.com/user-attachments/files/15888424/No_turbine_stable_.txt)
[No_Turbine_unstable_.txt](https://github.com/user-attachments/files/15888425/No_Turbine_unstable_.txt)

3) A general question, when my simulations successfully completed, I got this message of  " Unused ParmParse Variables", can someone explain what does that mean, are those variables unused in the simulations ?
![unused_parm_2](https://github.com/Exawind/amr-wind/assets/156853074/0a84edfa-820e-448a-ae5c-db4d3c7fbcca)
![unused_parm_1](https://github.com/Exawind/amr-wind/assets/156853074/3aaa272d-5e99-48da-b9b1-314fbfe580b6)

4) One of the experts from NREL suggested that when I am using OpenFAST with AMR-Wind, I should set “OpenMP flag to OFF” (https://forums.nrel.gov/t/tower-strike-with-latest-versions-of-openfast-and-iea-15mw/3024/84?u=raja.asim), my question is that should I set this flag to be Off for AMR-Wind too? (And can someone please comment on what will be the difference and implications, it will be helpful for new users like me, who have little knowledge about it)
Thanks in advance.

**Comment by marchdf** [comment]
I can answer some of these easily. Others might want to way in for the other questions.

1-2. Looks like there are some CFL violations. I would turn down the time step. Or use a variable time step.
3. "Unused ParmParse Variables": this has no impact on the simulation other than to tell the user that certain lines (inputs) in your input file were not used by the simulation. If you expected that, great, you can remove the lines from your input file and go on with things. Or just leave them in. If you didn't expect that, then you have an indication that you aren't doing what you thought you were doing ("huh that's weird I thought it would be using that input variable... I must have forgotten something else in the input file, maybe I forgot to turn on the physics I wanted")
4. Yes openmp should be off for openfast (since many compilers complain about their usage of openmp). You probably want to set it to off in amr-wind as well though I don't think you have to. The question is: do you want to use openmp threading? This option might give a tiny boost on CPU (won't make a difference on GPU). But then you have an extra parameter to play with : threads/rank and how big of a thread block you want. All of which are performance tuning knobs that will be architecture dependent so you would have to discover those for your own architecture. Also (and this is work in progress) not all loops in amr-wind are threaded so you wont see much performance change there either. All in all, I wouldn't bother with openmp (and that will probably change in the future because these things always do).

**Comment by AsimUdel** [comment]
Hi @marchdf ,
Thank you so much for your answers.
1-2) I have re-run the simulations with the variable time step.
3) I wanted those variables in my simulations i.e., to have  Stable atmospheric stability I gave certain value for "Abl.surface_temp_rate", which was not used.
4) Thank you, this is a bit technical, let me first see my architecture and then I can comment on this.
I will leave this issue open for few days, maybe someone else might jump in, then I'll close it.

**Comment by moprak-nrel** [comment]
Hi @AsimUdel, closing this issue as it looks like your questions have been addressed. Feel free to reopen if there are any follow-ups.
