### ISSUE TITLE
Sampling Warning 

### ISSUE THREAD

**Issue by hgopalan** [Exawind/amr-wind#1191]
I have been running sampling on the immersed forcing and never got this warning before. I get the warning message 

WARNING: Sampling: Non-existent field requested: terrain_blank. This is a mistake or the requested field is a derived field and should be added to the derived_fields parameter

The only difference is the change of the terrain_blank field from a regular field to an int_field. I declare and register the int field in here: https://github.com/hgopalan/amr-wind/blob/hgopalan-terrain/amr-wind/physics/TerrainDrag.cpp. I can see the field in the plt files. 

and in the sampling column add 

incflo.post_processing                = box_hr box_lr
box_lr.fields           = velocity terrain_blank

Do I need to change fields to int_field for sampling?

**Comment by moprak-nrel** [comment]
I think I know where the issue is, as you guessed, this is due to `terrain_blank` being an `int` field. The sampler checks whether a field exists by calling
https://github.com/Exawind/amr-wind/blob/741cb77111da01fe7026512f0a0cfdb3b9072398/amr-wind/utilities/sampling/Sampling.cpp#L53
But, `int` fields have a separate register, that can only be queried using `repo.int_field_exists(...)`
https://github.com/Exawind/amr-wind/blob/741cb77111da01fe7026512f0a0cfdb3b9072398/amr-wind/core/FieldRepo.cpp#L293

There is currently no sampling defined for int fields, let me think about the right fix.

**Comment by mbkuhn** [comment]
I don't think we've had cases in the past where there was an interest in sampling int fields. Similar to how we have "fields" and "derived_fields" separated, we may want to add another possible line of "int_fields". This is also how it is handled for plot file outputs. We'll just have to make sure we treat things properly in sample_field. Typically, sampled quantities are interpolated. Idk if int fields should be interpolated or if the integer value in the cell containing the sample point should be reported directly.
