### ISSUE TITLE
Specify initial velocity as a profile

### ISSUE THREAD

**Issue by cmkaul** [Exawind/amr-wind#375]
I need to specify initial velocity as a profile (rather than as a value that is constant in height) for a simulation I would like to perform, similar to the existing capability to supply a potential temperature profile. I see this listed as a "TODO" in wind_energy/ABLFieldInit.cpp. Are there any plans to move forward with adding this capability?

**Comment by sayerhs** [comment]
@cmkaul We can add that capability as it wouldn't take a lot of time. There is a similar functionality with user-defined functions (https://github.com/Exawind/amr-wind/blob/main/test/test_files/freestream_godunov/freestream_godunov.i#L35-L36) that could be repurposed in ABL physics. 

Also @shashankNREL has been working on using a NetCDF file to use WRF velocity/temperature profile to force the precursor simulation. He can share his development branch with you if you're interested in going that route.

**Comment by cmkaul** [comment]
Thanks @sayerhs. The development by @shashankNREL might be the best route, if he can share that. I'm trying to initialize from observed soundings rather than WRF outputs, but conceptually it should all be quite similar.

**Comment by sayerhs** [comment]
@shashankNREL all the more motivation to submit a PR and get the code merged to mainline ;)

**Comment by shashankNREL** [comment]
@cmkaul : Please take a look at my branch where I am initializing and forcing using a WRF output (https://github.com/shashankNREL/amr-wind/blob/2a0ad08e19cab01ae31c4f4adbecd6ef06b90caf/amr-wind/wind_energy/ABLFieldInit.cpp#L12). Let me know if you have any questions. 
@sayerhs : absolutely once I finish this validation case and put together a verification test case. I agree we should push this mainline so that all amr-wind users rely on main instead of user specific branches.

**Comment by cmkaul** [comment]
@shashankNREL, thank you.
