### ISSUE TITLE
Regression tests not setup properly to fail with different results 

### ISSUE THREAD

**Issue by sayerhs** [Exawind/amr-wind#40]
Currently regression tests are using `fcompare` utility to merely compare the run with a gold run and report/print out differences. `fcompare` utility still returns a success code when it returns and, therefore, the tests always pass as long as there are no problems with execution but the results are different. 

Two options:
- ~Introduce a check by processing the output of `fcompare`~ Run regression tests without MPI :(
- Change testing behavior to instead use `fextrema` and then compare the difference against gold files using `fextrema_compare.py` 

The latter option means the gold files will just be text (whitespace delimited table) files and can be easily stored with the repo unlike our current situation, and allows us to do testing in CI environments. However, adds an additional dependency for python packages: pandas and numpy.

**Comment by sayerhs** [comment]
[See here](https://github.com/AMReX-Codes/amrex/blob/7d788fbc54639401a5b4ee535af179af5d0ab27f/Tools/Plotfile/fcompare.cpp#L360-L370) for the reason why I think that `fcompare` when run within CTest returns a success result. It only seems to return the success/failure code from comparison when compiled without MPI 

```
int main (int argc, char* argv[])
{
    amrex::SetVerbose(0);
    amrex::Initialize(argc, argv, false);
    int r = main_main();
    ignore_unused(r);
    amrex::Finalize();
#ifndef BL_USE_MPI
    return r;
#endif
}```

**Comment by jrood-nrel** [comment]
Interesting. I didn't realize `fcompare` was doing that. I think you're crossed out suggestion is valid. What if we process the `fcompare` output like they do in the `amrex_testing` repo and we just store the `fcompare` output?

```
    regex = "\s+"
    words = re.split(regex, stdout)

    indices = filter(lambda i: words[i] in vars, range(len(words)))

    for i in indices:
        var, abs_err, rel_err = words[i: i + 3]
        if abs(test.tolerance) <= abs(float(rel_err)): return False

    return True
```

**Comment by sayerhs** [comment]
@jrood-nrel For nightly regression tests I think `fcompare` is preferrred. However, for Travis CI `fextrema` is probably better.

**Comment by sayerhs** [comment]
@jrood-nrel `fcompare` would still require the full `plt` files for it to generate the the `rel_err` correct? So while it makes sense for nightly-regression testing, I am not sure if it is good for Travis CI. `fextrema` on the other hand depends only on the `plt` files generated by the run.

**Comment by jrood-nrel** [comment]
Yeah now that I think about it, we need gold plot files for `fcompare` to work. I guess this is why we made the `fextrema` gold option originally. I started to not like the `fextrema` golds for PeleC because at one point they were difficult to match output on a local system with Travis CI, so they were difficult to update.

**Comment by jrood-nrel** [comment]
Looking at this further, in PeleC I would build `fcompare` without MPI manually, and PeleC with MPI so that is why it always failed on diffs. However, now that I'm using AMReX's CMake for `fcompare` (which didn't exist in AMReX until I asked for it) it looks like it inherits MPI. So now I understand why this is happening. I think I might just ask AMReX if they can have `fcompare` fail correctly with MPI.

**Comment by jrood-nrel** [comment]
This should be solved by https://github.com/AMReX-Codes/amrex/commit/feff0a586a329042a351d4a89e5ec4f99bdb56b1
