### ISSUE TITLE
Strong and Weak Scaling of AMR-Wind in Summit

### ISSUE THREAD

**Issue by tchatte3** [Exawind/amr-wind#465]
Hi @sayerhs @michaeljbrazell @shashankNREL I am seeing the following scaling trends in summit
I am simulating horizontally periodic domain with 2 layers of mesh refinement

![image](https://user-images.githubusercontent.com/14302216/128219345-2e74b8cc-4cbb-4c25-b712-4852b740c385.png)
![image](https://user-images.githubusercontent.com/14302216/128219462-0f5784bb-7729-4010-94cc-91664047b507.png)
![image](https://user-images.githubusercontent.com/14302216/128219574-585ec49c-9d3a-4545-aa0c-d93a0594cdad.png)

Some observations:
* In GPU, the strong scaling drops significantly past 10^22 cells/GPU
*  The strong scaling deviation from ideal scaling follows similar trends without (0 turbines) and with (20 turbines)
*  The overhead of the turbines added in the simulation ``OpenFAST`` overhead is approximately ``3 percent per turbine`` (2nd Figure) and 50% overhead for 20 turbine simulations. 
* Most of the work done in OpenFAST is through `
![image](https://user-images.githubusercontent.com/14302216/128230595-4505b46a-48dd-4db8-8020-d629eac4c81e.png)

(using TinyPRofiler)

**I wonder if there are any suggestions/thoughts that we can do to improve the turbine-overhead in AMR-wind?**

I have played around with the AMR-wind max_grid_size (64, 128)
e.g., changing max_grid_size to 64 from 128, I have seen 
* 17% improvement in scaling for 48 GPU
*  6% overhead in the scaling for 96 GPU

**Comment by sayerhs** [comment]
Regarding `scatter2` timings: https://github.com/Exawind/amr-wind/blob/650998941d68cca0e236081be0dd13aa43d33975/amr-wind/wind_energy/actuator/turbine/fast/turbine_fast_ops.H#L473-L474

Can you please make sure that the timings are generated with an MPI Barrier between `fast_step` and `scatter_data` here: https://github.com/Exawind/amr-wind/blob/650998941d68cca0e236081be0dd13aa43d33975/amr-wind/wind_energy/actuator/turbine/fast/turbine_fast_ops.H#L370-L373

Otherwise, `scatter2` is accounting for time spent in advancing OpenFAST time step.

**Comment by tchatte3** [comment]
@sayerhs Are you suggesting calling the BL_PROFILE for amr-wind::actuator::ComputeForceOp<TurbineFast>::scatter2" inside line 370 - 373 in turbine_fast_ops.H  and **remove** the other BL_PROFILE() calls.

Right now, the BL_PROFILE() is being called during broadcasting from root to other processes in turbine_fast_ops.H

```bash
// Broadcast data to all influenced procs from the root process
        const auto& procs = data.info().procs;
        const int tag = 1001;
        if (data.info().is_root_proc) {
            BL_PROFILE(
                "amr-wind::actuator::ComputeForceOp<TurbineFast>::scatter2");
            for (const int ip : procs) {
                if (ip == data.info().root_proc) continue;

                amrex::ParallelDescriptor::Send(
                    buf.data(), dsize, ip, tag, data.meta().tcomm);
            }
        } else {
            BL_PROFILE(
                "amr-wind::actuator::ComputeForceOp<TurbineFast>::scatter2");
            amrex::ParallelDescriptor::Recv(
                buf.data(), dsize, data.info().root_proc, tag,
                data.meta().tcomm);
        }
```

**Comment by sayerhs** [comment]
@tchatte3 No, that won't work. What's happening is that not all MPI ranks call FAST routines in  `fast_step` only 1 process per turbine will do that (determined by `is_root_proc`). So what is happening is that the for a given turbine, all other processes go straight to L475 and wait for the root process to finish its work and process the `Send` call. So the time spent in OpenFAST is getting accounted for in `scatter2` timings. I suspect you'll likely notice a huge difference between `min/max` timings for `scatter2`. So I was suggesting that to get an exact picture of the overhead of `Recv` calls (especially with many turbines), we will need a barrier and split out time spent in OpenFAST vs. time spent in MPI Send/Recv calls. 

Also as I commented on #466, it would be good to ensure that if you are running `MPI size > num turbines` that each turbine FAST instance is in a different MPI rank so that the turbine executions are not waiting on each other.

**Comment by tchatte3** [comment]
@sayerhs 
Yes, indeed 
``` bash
 amr-wind::actuator::ComputeForceOp<TurbineFast>::scatter2             355   0.009631      49.21      98.98  24.33%
```
Min is 0.009631 and Max is 98.98.

I see what you say. So, essentially I would need to get timing info between L370 - L373 : could you suggest the command call to print out timings. Should I take help of BL_PROFILE() here ? 

Also, I am not sure how to print the ranks for each turbine for the FAST instance in AMR-Wind. I am new to AMR-wind, could you kindly suggest the command.

Best,
Tanmoy

**Comment by sayerhs** [comment]
@tchatte3 I would do the following:

- after L370 add https://github.com/Exawind/amr-wind/blob/650998941d68cca0e236081be0dd13aa43d33975/amr-wind/wind_energy/actuator/turbine/fast/turbine_fast_ops.H#L370-L373

```C++
amrex::ParallelDescriptor::Barrier();
```

- After L377 add https://github.com/Exawind/amr-wind/blob/650998941d68cca0e236081be0dd13aa43d33975/amr-wind/wind_energy/actuator/turbine/fast/turbine_fast_ops.H#L376-L378  

```C++
BL_PROFILE("amr-wind::actuator::ComputeForceOp<TurbineFast>::fast_step");
```

**Comment by tchatte3** [comment]
@sayerhs : makes sense, thanks for helping with the commands.

**Comment by psakievich** [comment]
Closing for now. Please reopen if further questions exist.
