### ISSUE TITLE
Wind speed estimate to 0, irregular pitching in AMR-Wind with OpenFAST (IEA15MW)

### ISSUE THREAD

**Issue by jfrederik-nrel** [Exawind/amr-wind#888]
Hi there,

Since the latest update of AMR-Wind, I am running into the issue that the OpenFAST wind speed estimator finds a wind speed of 0. Subsequently, the pitch controller pitches the blades to an angle of approximately 3.4 degrees - which I am guessing is the region I collective pitch angle.

Run files are added.

@tonyinme @mbkuhn @gantech any of you perhaps able to help me?
[amr-bug-files.zip](https://github.com/Exawind/amr-wind/files/12177115/amr-bug-files.zip)

**Comment by tonyinme** [comment]
It looks like the velocities have an issue when sampling exactly on the faces/centers. 

https://github.com/Exawind/amr-wind/pull/868

**Comment by tonyinme** [comment]
The issue seems to have been that in the first time-step the MAC velocities are zero. 
A potential fix is using the old sampling approach in the very first time-step by adding a flag in this if statement. 

https://github.com/Exawind/amr-wind/blob/761b26dc2a542b4c7c8ba47d6ba8482c3dfdfe8b/amr-wind/wind_energy/actuator/Actuator.cpp#L191

**Comment by tonyinme** [comment]
This PR should address this issue.

https://github.com/Exawind/amr-wind/pull/889
